name: Publish CI

on:
  push:
    branches: ["zero"]
  pull_request:
    branches: ["zero"]

env:
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "1.8"
          distribution: "oracle"
      - run: |
          ./gradlew build
      - name: Upload Apk file
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
