name: Publish CI

on:
  push:
    tags:
      - "v*"

env:
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}
  TAG: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: "temurin"
      - run: |
          ./gradlew build
      - name: Create Release
        id: create_release
        uses: igorrs/create-release@v1
        env:
          GITHUB_TOKEN: ${{ env.PASS }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      # - name: Upload Apk file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app
      #     path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload Apk file
        uses: actions/upload-pages-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
          repo-token: ${{ env.PASS }}
          content-type: application/apk
