name: Publish CI

on:
  push:
    tags:
      - "v*"

env:
  USER: ${{ github.actor }}
  PASS: ${{ secrets.GITHUB_TOKEN }}
  TAG: ${{ github.ref }}
  TAG_NAME: ${{ github.ref_name }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup Java
      #   uses: actions/setup-java@v4
      #   with:
      #     java-version: 17
      #     distribution: "temurin"
      #
      # - name: Build project
      #   run: |
      #     ./gradlew Build

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ env.TAG_NAME }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
        run: |
          gh release create "$tag" --title "${tag#v}" --notes "$body"

      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
          tag: ${{ env.TAG_NAME }}
          asset_path: ./gradle.properties
          asset_name: zero.apk
        run: |
          gh release upload "$tag" "$asset_path#$asset_name"

      # - name: Create release
      #   id: create_release
      #   uses: igorrs/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ env.PASS }}
      #   with:
      #     tag_name: ${{ env.TAG }}
      #     release_name: Release ${{ env.TAG }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
      #
      # - name: Upload release assets
      #   id: upload-release-asset
      #   uses: sekwah41/upload-release-assets@v1
      #   env:
      #     GITHUB_TOKEN: ${{ env.PASS }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: app/build/outputs/apk/debug/app-debug.apk
      #     asset_name: app-${{ env.TAG_NAME }}.apk
      #     asset_content_type: application/apk
